services:
  gateway-service: # Имя сервиса для внутренней сети
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    container_name: gateway-service
    ports:
      - "8088:8080"
    depends_on:
      redis-cache: # Исправлено: имя сервиса Redis из твоего docker ps
        condition: service_started
      keycloak-auth: # Исправлено: имя сервиса Keycloak из твоего docker ps
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_REDIS_HOST=redis-cache
      - SPRING_REDIS_PORT=6379
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak-auth:8080/realms/master
      # Прокидываем URL-ы микросервисов явно для надежности
      - MONITORING_SERVICE_URL=http://monitoring-service:8080
      - DATA_UNIFIER_SERVICE_URL=http://data-unifier-service:8080
    networks:
      - platform-net
    restart: unless-stopped

networks:
  platform-net:
    driver: bridge
