spring:
  redis:
    host: redis-cache
    port: 6379
  cloud:
    gateway:
      routes:
        - id: monitor-route
          uri: http://monitoring-service:8080
          predicates:
            - Path=/monitor/**
        - id: data-route
          uri: http://data-unifier-service:8080
          predicates:
            - Path=/data/**

management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway, prometheus  # убедись, что prometheus тут есть
  endpoint:
    prometheus:
      enabled: true


